version: "3"

services:
  backend:
    image: ceos17/ceos-backend-dev
    container_name: backend
    hostname: backend
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - mysql

  nginx:
    image: ceos17/ceos-nginx-dev
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ceos-dev
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
