version: "3"

services:
  backend-dev:
    image: ceos17/ceos-backend-dev
    container_name: backend-dev
    hostname: backend-dev
    expose:
      - "8080"

  nginx:
    depends_on:
      - backend-dev
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    ports:
      - "80:80"

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"