version: "3"

services:
  backend:
    image: ceos17/ceos-backend
    container_name: backend
    hostname: backend
    env_file:
      - .env
    expose:
      - "8080"

  nginx:
    image: ceos17/ceos-nginx
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"